# Generated by Django 3.0.6 on 2020-06-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classschedule', '0002_auto_20200529_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newschedule',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
